### ISSUE TITLE
update b-tagging working points

### ISSUE THREAD

**Issue by pablodecm** [piedraj/AnalysisCMS#5]
The working points [used](https://github.com/piedraj/AnalysisCMS/blob/master/include/Constants.h#L124) are obsolete.
I suggest changing to the ones provided at:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation74X

**Comment by piedraj** [comment]
Thank you Pablo, the b-tagging working points have been updated.
